work_dir: ./work_dir/recognition/ntu-csub/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  data_path: ./data/NTU-RGB-D/csub/train_data.npy
  label_path: ./data/NTU-RGB-D/csub/train_label.pkl
test_feeder_args:
  data_path: ./data/NTU-RGB-D/csub/val_data.npy
  label_path: ./data/NTU-RGB-D/csub/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [3]
batch_size: 32
test_batch_size: 64
num_epoch: 80



