# command line: main.py skeleton_lrp --use_gpu False

batch_size: 256
cam_type: gradcam
config: ./config/st_gcn/ntu-xsub/demo_skeleton_cam.yaml
data_level: test_set
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
height: 1080
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 60
model_fps: 30
num_epoch: 80
num_worker: 4
openpose: null
output_dir: ./data/lrp_skeleton/result
pavi_log: false
phase: test
plot_action: true
print_log: false
save_interval: 10
save_log: true
save_result: false
skeleton: S001C001P001R001A006
start_epoch: 0
test_batch_size: 64
test_feeder_args:
    data_path: ./data/NTU-RGB-D/xsub/val_data.npy
    label_path: ./data/NTU-RGB-D/xsub/val_label.pkl
topk:
- 1
- 5
train_feeder_args: {}
use_gpu: false
valid: xsub
weights: ./models/st_gcn.ntu-xsub.pt
work_dir: ./work_dir/tmp
