weights: ./models/st_gcn.ntu-csetup.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU-RGB-D/csetup/val_data.npy
  label_path: ./data/NTU-RGB-D/csetup/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 120
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: 2
test_batch_size: 1

